--PREVENT TABLE DROPS FOR NONSUPERUSER
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

--BASIC PERMISSIONS FOR MANAGER ROLE
GRANT INSERT, SELECT, UPDATE ON TABLE [] TO manager;


--MANAGER USAGE FOR SEQUENCES
GRANT USAGE ON SEQUENCE [].alias_ids_id_seq TO manager;



--PERMISSIONS FOR VIEWER ROLE
GRANT SELECT ON [] TO viewer;